name: Docker Image CI

on: push
    
jobs:
  release:
    name: Create Github release
    runs-on: ubuntu-20.04
    if: startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md
          generate_release_notes: true

  build:
    name: Build docker images
    if: startsWith(github.event.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/vforwater/tbr_template_r

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
